"""Never changing lists."""

towns = ['Baragoi',
         'Bungoma',
         'Busia',
         'Butere',
         'Dadaab',
         'Diani Beach',
         'Eldoret',
         'Emali',
         'Embu',
         'Garissa',
         'Gede',
         'Hola',
         'Homa Bay',
         'Isiolo',
         'Kitui',
         'Kibwezi',
         'Makindu',
         'Wote',
         'Mutomo',
         'Kajiado',
         'Kakamega',
         'Kakuma',
         'Kapenguria',
         'Kericho',
         'Kiambu',
         'Kilifi',
         'Kisii',
         'Kisumu',
         'Kitale',
         'Lamu',
         'Langata',
         'Litein',
         'Lodwar',
         'Lokichoggio',
         'Londiani',
         'Loyangalani',
         'Machakos',
         'Malindi',
         'Mandera',
         'Maralal',
         'Marsabit',
         'Meru',
         'Mombasa',
         'Moyale',
         'Mumias',
         'Muranga',
         'Nairobi',
         'Naivasha',
         'Nakuru',
         'Namanga',
         'Nanyuki',
         'Naro Moru',
         'Narok',
         'Nyahururu',
         'Nyeri',
         'Ruiru',
         'Shimoni',
         'Takaungu',
         'Thika',
         'Vihiga',
         'Voi',
         'Wajir',
         'Watamu',
         'Webuye',
         'Wundanyi']

makes = [{'id': 136, 'name': 'ABARTH'},
         {'id': 141, 'name': 'Acura'},
         {'id': 38, 'name': 'Alfa Romeo'},
         {'id': 58, 'name': 'AMC'},
         {'id': 32, 'name': 'AMG'},
         {'id': 18, 'name': 'Aston Martin'},
         {'id': 26, 'name': 'Audi'},
         {'id': 51, 'name': 'Austin'},
         {'id': 37, 'name': 'Autobianche'},
         {'id': 21, 'name': 'Bentley'},
         {'id': 48, 'name': 'Birkin'},
         {'id': 23, 'name': 'BMW'},
         {'id': 24, 'name': 'BMW Alpina'},
         {'id': 247, 'name': 'BOMAG'},
         {'id': 126, 'name': 'Cadillac'},
         {'id': 72, 'name': 'Carbodies'},
         {'id': 112, 'name': 'CAT'},
         {'id': 74, 'name': 'Caterham'},
         {'id': 243, 'name': 'Caterpillar'},
         {'id': 127, 'name': 'Chevrolet'},
         {'id': 12, 'name': 'Chrysler'},
         {'id': 33, 'name': 'Citroen'},
         {'id': 55, 'name': 'Daewoo'},
         {'id': 158, 'name': 'Daf'},
         {'id': 8, 'name': 'Daihatsu'},
         {'id': 87, 'name': 'Detomaso'},
         {'id': 131, 'name': 'Dodge'},
         {'id': 67, 'name': 'Europe Ford'},
         {'id': 40, 'name': 'Ferrari'},
         {'id': 39, 'name': 'Fiat'},
         {'id': 16, 'name': 'Ford'},
         {'id': 71, 'name': 'Germany Others'},
         {'id': 11, 'name': 'GM'},
         {'id': 59, 'name': 'GMC'},
         {'id': 61, 'name': 'Hino'},
         {'id': 119, 'name': 'Hitachi'},
         {'id': 199, 'name': 'Holden'},
         {'id': 3, 'name': 'Honda'},
         {'id': 128, 'name': 'Hummer'},
         {'id': 56, 'name': 'Hyundai'},
         {'id': 140, 'name': 'Infiniti'},
         {'id': 9, 'name': 'Isuzu'},
         {'id': 168, 'name': 'Iveco'},
         {'id': 19, 'name': 'Jaguar'},
         {'id': 244, 'name': 'JCB'},
         {'id': 130, 'name': 'Jeep'},
         {'id': 114, 'name': 'Kato'},
         {'id': 47, 'name': 'Kia Motors'},
         {'id': 115, 'name': 'Kobelco'},
         {'id': 116, 'name': 'Komatsu'},
         {'id': 256, 'name': 'Kubota'},
         {'id': 43, 'name': 'Lamborghini'},
         {'id': 42, 'name': 'Lancia'},
         {'id': 62, 'name': 'Land Rover'},
         {'id': 122, 'name': 'Lexus'},
         {'id': 250, 'name': 'Liebherr'},
         {'id': 132, 'name': 'Lincoln'},
         {'id': 53, 'name': 'Lotus'},
         {'id': 176, 'name': 'MAN'},
         {'id': 41, 'name': 'Maserati'},
         {'id': 5, 'name': 'Mazda'},
         {'id': 54, 'name': 'MCC'},
         {'id': 31, 'name': 'Mercedes-Benz'},
         {'id': 49, 'name': 'MG'},
         {'id': 4, 'name': 'Mitsubishi'},
         {'id': 338, 'name': 'Mitsubishi Fuso'},
         {'id': 10, 'name': 'Mitsuoka'},
         {'id': 76, 'name': 'Moke'},
         {'id': 52, 'name': 'Morgan'},
         {'id': 77, 'name': 'Morris'},
         {'id': 2, 'name': 'Nissan'},
         {'id': 28, 'name': 'Opel'},
         {'id': 65, 'name': 'Other All'},
         {'id': 63, 'name': 'Panther'},
         {'id': 34, 'name': 'Peugeot'},
         {'id': 30, 'name': 'Porsche'},
         {'id': 201, 'name': 'Proton'},
         {'id': 35, 'name': 'Renault'},
         {'id': 20, 'name': 'Rolls-Royce'},
         {'id': 22, 'name': 'Rover'},
         {'id': 44, 'name': 'Saab'},
         {'id': 13, 'name': 'Saturn'},
         {'id': 182, 'name': 'Scania'},
         {'id': 135, 'name': 'Smart'},
         {'id': 104, 'name': 'Ssangyong'},
         {'id': 6, 'name': 'Subaru'},
         {'id': 118, 'name': 'Sumitomo'},
         {'id': 7, 'name': 'Suzuki'},
         {'id': 95, 'name': 'Sweden Others'},
         {'id': 246, 'name': 'TAKEUCHI'},
         {'id': 120, 'name': 'TCM'},
         {'id': 251, 'name': 'Terex'},
         {'id': 1, 'name': 'Toyota'},
         {'id': 82, 'name': 'Triumph'},
         {'id': 84, 'name': 'U.K. Others'},
         {'id': 103, 'name': 'U.S.A. Others'},
         {'id': 29, 'name': 'Volkswagen'},
         {'id': 45, 'name': 'Volvo'},
         {'id': 73, 'name': 'Westfield'},
         {'id': 50, 'name': 'Winnebago'},
         {'id': 245, 'name': 'YANMAR'}]

models = {}
